import { CYBER_COLORS, CYBER_STYLES, NEON_GLOW, TEXT_GLOW } from "@/constants/theme";
import { fontScale, hp, wp } from "@/utils/responsive";
import { StyleSheet } from "react-native";

export const secondaryStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: CYBER_COLORS.background.primary,
  },
  header: {
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(4),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CYBER_COLORS.background.secondary,
    borderBottomWidth: 1,
    borderBottomColor: CYBER_COLORS.neon.cyanDim,
  },
  backButton: {
    position: 'absolute',
    left: wp(3),
    paddingVertical: hp(0.5),
    paddingHorizontal: wp(2),
    backgroundColor: CYBER_COLORS.background.card,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: CYBER_COLORS.neon.cyanDim,
  },
  backButtonText: {
    color: CYBER_COLORS.neon.cyan,
    fontSize: fontScale(11),
    fontWeight: 'bold',
  },
  title: {
    color: CYBER_COLORS.text.primary,
    fontSize: fontScale(18),
    fontWeight: 'bold',
    ...TEXT_GLOW.cyan,
  },
  stateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(4),
  },
  readyContainer: {
    flex: 1,
  },
  readyContent: {
    paddingHorizontal: wp(4),
    paddingTop: hp(2),
    paddingBottom: hp(4),
  },
  readyBox: {
    alignItems: 'center',
    paddingVertical: hp(2),
    paddingHorizontal: wp(4),
    backgroundColor: CYBER_COLORS.background.card,
    borderRadius: 16,
    borderWidth: 2,
    marginBottom: hp(2),
  },
  infantryBox: {
    borderColor: CYBER_COLORS.neon.cyan,
    ...NEON_GLOW.cyan,
  },
  cavalryBox: {
    borderColor: CYBER_COLORS.neon.magenta,
    shadowColor: '#FF00FF',
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 10,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(0.5),
  },
  readyEmoji: {
    fontSize: fontScale(24),
    marginRight: wp(2),
  },
  readyTitle: {
    fontSize: fontScale(20),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
    marginBottom: hp(0.5),
    ...TEXT_GLOW.cyan,
  },
  readyDescription: {
    fontSize: fontScale(13),
    color: CYBER_COLORS.text.secondary,
    textAlign: 'center',
  },
  specCard: {
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(4),
    backgroundColor: CYBER_COLORS.background.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CYBER_COLORS.neon.cyanDim,
    marginBottom: hp(2),
  },
  specCardTitle: {
    fontSize: fontScale(14),
    fontWeight: 'bold',
    color: CYBER_COLORS.neon.cyan,
    marginBottom: hp(1.5),
  },
  specRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: hp(0.8),
  },
  specLabel: {
    fontSize: fontScale(12),
    color: CYBER_COLORS.text.muted,
  },
  specValue: {
    fontSize: fontScale(13),
    color: CYBER_COLORS.text.primary,
  },
  specValueHighlight: {
    fontSize: fontScale(14),
    fontWeight: 'bold',
    color: CYBER_COLORS.neon.cyan,
    ...TEXT_GLOW.cyan,
  },
  specDivider: {
    height: 1,
    backgroundColor: CYBER_COLORS.neon.cyanDim,
    marginVertical: hp(1),
  },
  calibrationRequired: {
    alignItems: 'center',
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(4),
    backgroundColor: 'rgba(255, 184, 0, 0.15)',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: CYBER_COLORS.status.warning,
    marginBottom: hp(2),
  },
  calibrationTitle: {
    fontSize: fontScale(13),
    fontWeight: 'bold',
    color: CYBER_COLORS.status.warning,
    marginBottom: hp(1),
    textAlign: 'center',
  },
  calibrateButton: {
    paddingVertical: hp(1),
    paddingHorizontal: wp(4),
    backgroundColor: 'rgba(255, 184, 0, 0.2)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CYBER_COLORS.status.warning,
  },
  calibrateButtonText: {
    fontSize: fontScale(13),
    fontWeight: 'bold',
    color: CYBER_COLORS.status.warning,
  },
  calibrationDone: {
    alignItems: 'center',
    paddingVertical: hp(1),
    paddingHorizontal: wp(4),
    backgroundColor: 'rgba(0, 255, 136, 0.15)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CYBER_COLORS.status.success,
    marginBottom: hp(2),
  },
  calibrationDoneText: {
    fontSize: fontScale(13),
    fontWeight: 'bold',
    color: CYBER_COLORS.status.success,
  },
  startButton: {
    paddingVertical: hp(1.5),
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 2,
  },
  infantryButton: {
    ...CYBER_STYLES.successButton,
  },
  cavalryButton: {
    backgroundColor: 'rgba(255, 0, 255, 0.2)',
    borderColor: CYBER_COLORS.neon.magenta,
    shadowColor: '#FF00FF',
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 10,
  },
  startButtonText: {
    fontSize: fontScale(16),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
  },
  measuringBox: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: hp(3),
    paddingHorizontal: wp(4),
    backgroundColor: CYBER_COLORS.background.card,
    borderRadius: 16,
    borderWidth: 2,
    marginBottom: hp(2),
  },
  infantryMeasuring: {
    borderColor: CYBER_COLORS.neon.cyan,
    ...NEON_GLOW.cyan,
  },
  cavalryMeasuring: {
    borderColor: CYBER_COLORS.neon.magenta,
    shadowColor: '#FF00FF',
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 10,
  },
  measuringTitle: {
    fontSize: fontScale(20),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
    marginBottom: hp(1),
  },
  measuringDescription: {
    fontSize: fontScale(14),
    color: CYBER_COLORS.text.secondary,
    textAlign: 'center',
  },
  liveDataBox: {
    width: '100%',
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(4),
    backgroundColor: CYBER_COLORS.background.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CYBER_COLORS.neon.cyanDim,
    marginBottom: hp(2),
  },
  liveDataRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: hp(0.6),
  },
  liveDataLabel: {
    fontSize: fontScale(12),
    color: CYBER_COLORS.text.muted,
  },
  liveDataValue: {
    fontSize: fontScale(13),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
  },
  liveDataValueMax: {
    fontSize: fontScale(15),
    fontWeight: 'bold',
    color: CYBER_COLORS.neon.cyan,
    ...TEXT_GLOW.cyan,
  },
  liveDataDivider: {
    height: 1,
    backgroundColor: CYBER_COLORS.neon.cyanDim,
    marginVertical: hp(0.5),
  },
  stopButton: {
    paddingVertical: hp(1.8),
    paddingHorizontal: wp(10),
    ...CYBER_STYLES.dangerButton,
    borderRadius: 14,
  },
  stopButtonText: {
    fontSize: fontScale(18),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
  },
  resultContainer: {
    flex: 1,
  },
  resultContent: {
    paddingHorizontal: wp(4),
    paddingTop: hp(2),
    paddingBottom: hp(4),
  },
  resultTitle: {
    fontSize: fontScale(20),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
    textAlign: 'center',
    marginBottom: hp(2),
    ...TEXT_GLOW.cyan,
  },
  resultMainCard: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: hp(18),
    paddingVertical: hp(2),
    paddingHorizontal: wp(4),
    backgroundColor: CYBER_COLORS.background.card,
    borderRadius: 16,
    borderWidth: 2,
    marginBottom: hp(1.5),
  },
  infantryResultCard: {
    borderColor: CYBER_COLORS.neon.cyan,
    ...NEON_GLOW.cyan,
  },
  cavalryResultCard: {
    borderColor: CYBER_COLORS.neon.magenta,
    shadowColor: '#FF00FF',
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 10,
  },
  resultEnergyValue: {
    fontSize: fontScale(36),
    fontWeight: 'bold',
    color: CYBER_COLORS.neon.cyan,
    marginTop: hp(1),
    lineHeight: fontScale(44),
  },
  resultEnergyUnit: {
    fontSize: fontScale(13),
    color: CYBER_COLORS.text.secondary,
  },
  resultDetailsCard: {
    paddingVertical: hp(1.2),
    paddingHorizontal: wp(4),
    backgroundColor: CYBER_COLORS.background.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CYBER_COLORS.neon.cyanDim,
    marginBottom: hp(1.5),
  },
  resultSectionTitle: {
    fontSize: fontScale(13),
    fontWeight: 'bold',
    color: CYBER_COLORS.neon.cyan,
    marginBottom: hp(1),
  },
  resultRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: hp(0.6),
    borderBottomWidth: 1,
    borderBottomColor: CYBER_COLORS.neon.cyanDim,
  },
  resultDetailLabel: {
    fontSize: fontScale(11),
    color: CYBER_COLORS.text.muted,
  },
  resultDetailValue: {
    fontSize: fontScale(12),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
  },
  formulaCard: {
    paddingVertical: hp(1.2),
    paddingHorizontal: wp(4),
    backgroundColor: CYBER_COLORS.background.secondary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CYBER_COLORS.neon.cyanDim,
    marginBottom: hp(1.5),
    alignItems: 'center',
  },
  formulaTitle: {
    fontSize: fontScale(13),
    fontWeight: 'bold',
    color: CYBER_COLORS.neon.cyan,
    marginBottom: hp(0.8),
  },
  formulaText: {
    fontSize: fontScale(10),
    color: CYBER_COLORS.text.secondary,
    marginBottom: hp(0.3),
  },
  formulaResult: {
    fontSize: fontScale(13),
    fontWeight: 'bold',
    color: CYBER_COLORS.neon.cyan,
    marginTop: hp(0.5),
    ...TEXT_GLOW.cyan,
  },
  nextButton: {
    paddingVertical: hp(1.5),
    alignItems: 'center',
    backgroundColor: 'rgba(255, 0, 255, 0.2)',
    borderWidth: 2,
    borderColor: CYBER_COLORS.neon.magenta,
    borderRadius: 14,
    shadowColor: '#FF00FF',
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 10,
  },
  nextButtonText: {
    fontSize: fontScale(15),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
  },
  finalButton: {
    paddingVertical: hp(1.5),
    alignItems: 'center',
    ...CYBER_STYLES.successButton,
    borderRadius: 14,
  },
  finalButtonText: {
    fontSize: fontScale(15),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
  },
  finalTitle: {
    fontSize: fontScale(22),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
    textAlign: 'center',
    marginBottom: hp(2),
    ...TEXT_GLOW.cyan,
  },
  comparisonCard: {
    padding: wp(4),
    backgroundColor: CYBER_COLORS.background.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: CYBER_COLORS.neon.cyanDim,
    marginBottom: hp(1.5),
    position: 'relative',
  },
  winnerCard: {
    borderWidth: 2,
    borderColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 10,
  },
  winnerBadge: {
    position: 'absolute',
    top: -hp(1.2),
    right: wp(3),
    backgroundColor: '#FFD700',
    paddingVertical: hp(0.3),
    paddingHorizontal: wp(2),
    borderRadius: 6,
    fontSize: fontScale(10),
    fontWeight: 'bold',
    color: '#000',
    overflow: 'hidden',
  },
  comparisonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(0.8),
  },
  comparisonEmoji: {
    fontSize: fontScale(22),
    marginRight: wp(2),
  },
  comparisonTitle: {
    fontSize: fontScale(15),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
  },
  comparisonEnergy: {
    fontSize: fontScale(28),
    fontWeight: 'bold',
    color: CYBER_COLORS.neon.cyan,
    textAlign: 'center',
    paddingVertical: hp(1),
    ...TEXT_GLOW.cyan,
  },
  comparisonDetails: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: wp(4),
    marginTop: hp(0.5),
  },
  comparisonDetailText: {
    fontSize: fontScale(10),
    color: CYBER_COLORS.text.muted,
  },
  comparisonSpec: {
    fontSize: fontScale(10),
    color: CYBER_COLORS.text.muted,
    textAlign: 'center',
    marginTop: hp(0.5),
  },
  analysisCard: {
    paddingVertical: hp(1.2),
    paddingHorizontal: wp(4),
    backgroundColor: 'rgba(0, 240, 255, 0.1)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CYBER_COLORS.neon.cyan,
    marginBottom: hp(1.5),
  },
  analysisTitle: {
    fontSize: fontScale(13),
    fontWeight: 'bold',
    color: CYBER_COLORS.neon.cyan,
    marginBottom: hp(1),
    textAlign: 'center',
  },
  analysisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: hp(0.5),
  },
  analysisLabel: {
    fontSize: fontScale(12),
    color: CYBER_COLORS.text.muted,
  },
  analysisValue: {
    fontSize: fontScale(13),
    fontWeight: 'bold',
    color: CYBER_COLORS.neon.cyan,
    ...TEXT_GLOW.cyan,
  },
  retryButton: {
    flex: 1,
    paddingVertical: hp(1.3),
    alignItems: 'center',
    ...CYBER_STYLES.neonButton,
    borderRadius: 14,
  },
  retryButtonText: {
    fontSize: fontScale(14),
    fontWeight: 'bold',
    color: CYBER_COLORS.text.primary,
  },
  viewShot: {
    flex: 1,
    backgroundColor: CYBER_COLORS.background.primary,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: wp(3),
    marginTop: hp(1),
  },
  captureButton: {
    flex: 1,
    paddingVertical: hp(1.3),
    alignItems: 'center',
    backgroundColor: 'rgba(255, 184, 0, 0.2)',
    borderWidth: 1,
    borderColor: CYBER_COLORS.status.warning,
    borderRadius: 14,
  },
  captureButtonText: {
    fontSize: fontScale(14),
    fontWeight: 'bold',
    color: CYBER_COLORS.status.warning,
  },
});
